### PR TITLE
Fix | Access token identity leaking across pooled connections

### LINKED ISSUE #1396: An existing connection in the connection pool is reused unexpectedly even though it has a different access token.
Please check the [FAQ (frequently-asked questions)](https://github.com/Microsoft/msphpsql/wiki/FAQ) first. If you have other questions or something to report, please address the following (skipping questions might delay our responses):

**PHP version**  
7.4.13 (I also confirmed with 7.1)

**PHP SQLSRV or PDO_SQLSRV version**  
5.8

**Microsoft ODBC Driver version**  
17.8

**SQL Server version**  
Azure SQL Database

**Client operating system**  
Windows Server 2016, Windows 10

**Table schema**  
N/A

**Problem description**  
After you open and close a connection to Azure SQL Database using the accessToken for a User-assigned managed ID, the second connection reuses the existing connection from the connection pool unexpectedly even though the accessToken of the new connection is different from the connection in the pool.

- This issue occurs when connection pooling is enabled.
- This issue doesn't occur if we call the same ODBC API in C++ application.
- As far as I saw the detail (Debugging), it looks that one of settings for the second connection (lpdbc in ODBC32) has the same value as the first connection and it causes the first connection to be reusable in ODBC32. As the setting comes from PHP, there might be something wrong, but I haven't determined, yet.

**Expected behavior and actual behavior**  
- Expected:
If the accessToken of a new connection is different from any connections in the connection pool, a new connection must be opened.

- Actual:
Although the acceesToken of a new connection is different from any connections in the connection pool, existing connection is reused.

**Repro code or steps to reproduce**
1) Create Azure SQL Server and SQL Database.
2) Create a service principal in Azure AD.
3) Configure Azure Active Directory admin in SQL Server to enable Azure AD authentication with the service principal.
https://docs.microsoft.com/en-us/azure/azure-sql/database/authentication-aad-configure?view=azuresql&tabs=azure-powershell
4) Create 2 User-assigned Managed ID (UMI).
5) Create 2 contained-database user in Azure SQL Database for UMI like this.
=====
Install-Module MSAL.PS
Import-Module MSAL.PS
$tenantId = "***Place your tenant ID***"
$clientId = "***Place your service principal's id***"
$clientSecret = "***Place your service principal's client secret***"
$scopes = "https://database.windows.net/.default"
$result = Get-MsalToken -RedirectUri $uri -ClientId $clientId -ClientSecret (ConvertTo-SecureString $clientSecret -AsPlainText -Force) -TenantId $tenantId -Scopes $scopes
$Tok = $result.AccessToken
$SQLServerName = "***Place your SQL Server name***"
$DatabaseName = "***Place your database name***"
$conn = New-Object System.Data.SqlClient.SQLConnection
$conn.ConnectionString = "Data Source=$SQLServerName.database.windows.net;Initial Catalog=$DatabaseName;Connect Timeout=30"
$conn.AccessToken = $Tok
$conn.Open()
$ddlstmt = "CREATE USER [***Place a new user name***] FROM EXTERNAL PROVIDER;"
$command = New-Object -TypeName System.Data.SqlClient.SqlCommand($ddlstmt, $conn)
$command.ExecuteNonQuery()
$conn.Close()
=====

6) Create a Azure VM.
7) Install PHP, Microsoft ODBC Driver for SQL Server and Microsoft Drivers for PHP for SQL Server.
8) Configure IIS which can run PHP.
9) Get access token for each user-assigned managed id.
10) Create a .php file and place it under wwwroot folder.
=====
`<?php
function connectsql($pooling, $accToken) {
    $azureAdDatabase = "***Place your database name***";
    $azureAdServer = "***Place your SQL Server name***";
    try {
        $connectionInfo = "Database = $azureAdDatabase; AccessToken = $accToken; ConnectionPooling = $pooling;";
        $conn = new PDO("sqlsrv:server = $azureAdServer; $connectionInfo");
        echo "Connected successfully with Azure AD Access Token\n";
        $tsql = "SELECT USER_NAME()";
        try {
            $stmt = $conn->query($tsql);
            $result = $stmt->fetchall(PDO::FETCH_ASSOC);
            unset($stmt);
        } catch (PDOException $e) {
            echo "Failed to run the simple query (user-assigned).\n";
        }
        unset($conn);

    } catch (PDOException $e) {
        echo "Could not connect with Azure AD Access Token.\n";
        $result = $e->getMessage();
    }
    return $result;
}
$token1 = "***Place a token for User-assigned Managed ID 1***";
$token2 = "***Place a token for User-assigned Managed ID 2***";
$ret = connectsql("true", $token1);
print_r($ret);
$ret = connectsql("true", $token2);
print_r($ret);
?>`
=====

### PR DESCRIPTION
**Pull request by David-Engel**
Fixes #1396

### Problem

When using AccessToken with connection pooling, two issues cause incorrect behavior:

1. Identity cross-contamination: The ODBC Driver Manager matches pooled connections by connection string but does not compare driver-specific attributes like `SQL_COPT_SS_ACCESS_TOKEN`. Connections to the same server with different access tokens share the same pool entry, returning the wrong identity to callers.

2. Use-after-free: The ODBC driver stores only the raw `ACCESSTOKEN` pointer — it never copies the token data. The previous code freed the token immediately after `SQLDriverConnect` returned. If the DM pooled the physical connection and idle connection recovery later fired, the driver would dereference freed memory.

### Solution

**Pool-key differentiation** - After building the connection string, a FNV-1a 64-bit hash of the token content is appended as `APP={AT-<hash>};`. This gives the DM a distinct pool key per token without affecting the ODBC driver's behavior. If the user also sets `APP`, the first occurrence determines the server-side program_name, but the DM sees the full string for pool matching.

**Token cache for pointer stability** - A process-wide token cache (`token_cache_get`) ensures the same raw token content always resolves to the same `ACCESSTOKEN*`. Tokens are allocated with `malloc` (not `emalloc`) so they persist across PHP requests. The `sqlsrv_conn::azure_ad_access_token` field is changed from an owning `sqlsrv_malloc_auto_ptr<ACCESSTOKEN>` to a non-owning `ACCESSTOKEN*` managed by the cache.

**TTL-based expiry** - Since there's no API hook for when physical connections are actually closed in the pool, cached tokens are removed after a configurable TTL derived from the ODBC driver's CPTimeout setting (TTL = max(CPTimeout × 2, 120s)). The TTL is read from ODBCINST.INI on Linux (`SQLGetPrivateProfileString`) and the Windows registry (`RegOpenKeyExA`/`RegQueryValueExA`) during MINIT. Token memory is scrubbed with `explicit_bzero`/`SecureZeroMemory` before being freed.

**Thread safety** - All cache operations are protected by `std::mutex`, safe for ZTS builds. `token_cache_touch()` updates the entry's timestamp before `SQLDisconnect()` returns the physical connection to the DM pool, closing a potential race window where another thread's cleanup could expire the entry.

#### Core driver (source/shared/):

`core_conn.cpp` - Token cache implementation (get/touch/expire/destroy/init_ttl), `secure_zero` helper, pool-key injection in `build_connection_string_and_set_conn_attr`, non-owning token reference in `core_sqlsrv_close` and `access_token_set_func`
`core_sqlsrv.h` - `core_sqlsrv_hash_fnv1a_64` inline function, cache init/cleanup declarations, `azure_ad_access_token` changed from `sqlsrv_malloc_auto_ptr<ACCESSTOKEN>` to raw pointer
`core_init.cpp` - `core_sqlsrv_init_token_cache()` called in MINIT, `core_sqlsrv_cleanup_token_cache()` called in MSHUTDOWN

#### Test infrastructure:

`test/tools/mock_tds_server.py` - Mock TDS 7.4 server (~1,450 lines) supporting LOGIN7, access token extraction, PRELOGIN, session recovery FeatureExtAck, KILL by SPID, TLS wrapping, and SELECT SUSER_SNAME() / @@SPID queries
`test/tools/test_mock_tds_server.py` - Unit tests for the mock server
`test/functional/sqlsrv/mock_tds_helper.inc` - Shared PHP helper for managing the mock server process and generating self-signed certificates
`test/functional/sqlsrv/sqlsrv_mock_access_token.phpt` / `pdo_sqlsrv/pdo_mock_access_token.phpt` - PHPT tests that connect with two different access tokens via the mock server and verify each connection returns the correct identity
`test/functional/sqlsrv/sqlsrv_mock_access_token_worker.php` / `pdo_sqlsrv/pdo_mock_access_token_worker.php` - Worker scripts for the above tests

#### Build:

`build-linux.sh` - Linux build script for both extensions
`.gitignore` - Ignore build artifacts from phpize/make

### CODE REVIEW

File: source/shared/core_conn.cpp [hunk 1]
```diff
@@ -79,6 +81,214 @@ bool core_search_odbc_driver_unix(_In_ ODBC_DRIVER driver);
...
+    TokenCacheEntry* next;
+};
+
+static TokenCacheEntry* s_token_cache = nullptr;
+static time_t s_token_cache_ttl = 120; // default floor; updated by token_cache_init_ttl()
+static std::mutex s_token_cache_mutex;
+
+// Minimum TTL floor (seconds).  Even if CPTimeout is very small, we keep
+// tokens alive for at least this long to account for in-flight recoveries.
+static const time_t TOKEN_CACHE_TTL_FLOOR = 120;
```
Comment (saurabh500) [inline source/shared/core_conn.cpp:121]: Out of curiosity, what was the thought process behind 120?

File: source/shared/core_sqlsrv.h [hunk 2]
```diff
@@ -1052,6 +1054,19 @@ extern HashTable* g_encodings;                    // encodings supported by this
 
 void core_sqlsrv_minit( _Outptr_ sqlsrv_context** henv_cp, _Inout_ sqlsrv_context** henv_ncp, _In_ error_callback err, _In_z_ const char* driver_func );
 void core_sqlsrv_mshutdown( _Inout_ sqlsrv_context& henv_cp, _Inout_ sqlsrv_context& henv_ncp );
+void core_sqlsrv_init_token_cache();
+void core_sqlsrv_cleanup_token_cache();
+
+// FNV-1a 64-bit hash used by both the token cache and APP pool-key generation.
+inline uint64_t core_sqlsrv_hash_fnv1a_64(const char* data, size_t len)
```
Comment (saurabh500) [inline source/shared/core_sqlsrv.h:1061]: I am curious about FNV-1a hash. Why was this used instead of collision resistant Sha256?

File: test/functional/pdo_sqlsrv/pdo_mock_access_token.phpt [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+On Linux/macOS, pooling is enabled via a custom odbcinst.ini with CPTimeout on
+each driver section and the test runs in a subprocess with ODBCSYSINI set.
+On Windows, pooling is controlled by the ConnectionPooling option.
+--SKIPIF--
+<?php
+if (!extension_loaded("pdo_sqlsrv")) {
+    die("skip pdo_sqlsrv extension not loaded");
+}
+require_once(__DIR__ . '/../sqlsrv/mock_tds_helper.inc');
+$mock = start_mock_tds_server();
```
Comment (saurabh500) [inline test/functional/pdo_sqlsrv/pdo_mock_access_token.phpt:20]: The legendary server !

File: test/functional/sqlsrv/mock_tds_helper.inc [hunk 4]
```diff
@@ -0,0 +1,398 @@
...
+    return strtoupper(substr(PHP_OS, 0, 3)) === 'WIN';
+}
+
+/**
+ * Find a working Python interpreter (python3 on Linux/macOS, python on Windows).
+ * Returns the command name, or null if not found.
+ */
+function find_python()
+{
+    $candidates = is_windows() ? ['python', 'python3'] : ['python3', 'python'];
```
Comment (saurabh500) [inline test/functional/sqlsrv/mock_tds_helper.inc]: Nit:
Why reverse the order? Are the chances of finding "python" higher on Windows ? For the sake of simplicity, can we not keep a single array on the two platforms?

File: source/shared/core_conn.cpp [hunk 5]
```diff
@@ -814,6 +1028,27 @@ void build_connection_string_and_set_conn_attr( _Inout_ sqlsrv_conn* conn, _Inou
...
+        // We use APP because it is a well-known keyword that won't cause
+        // warnings.  If the user already set APP, the first occurrence wins
+        // for the server-side program_name, but the DM still sees the full
+        // string (including our duplicate) for pool-key matching.
+        if (access_token_used && conn->azure_ad_access_token) {
+            ACCESSTOKEN* tok = conn->azure_ad_access_token;
+            uint64_t h = core_sqlsrv_hash_fnv1a_64(
+                tok->data, static_cast<size_t>(tok->dataSize));
+            char pool_key[64];
+            snprintf(pool_key, sizeof(pool_key),
```
Comment (saurabh500) [inline source/shared/core_conn.cpp:1047]: Is it OK to override the APP? if the App is set in the PHP connection string, then this line should override it, isn't it? And this will get sent to the server as well.
Or are we blocking the App from conn str like Python ?

File: test/functional/pdo_sqlsrv/pdo_mock_access_token.phpt [hunk 6]
```diff
@@ -0,0 +1,67 @@
...
+$mock = start_mock_tds_server([
+    '--map-token', "$tokenA=alice",
+    '--map-token', "$tokenB=bob",
+]);
+
+$server = "127.0.0.1,{$mock['port']}";
+
+// On Linux/macOS, create custom odbcinst.ini with pooling enabled.
+// On Windows, this returns null (pooling is controlled via ConnectionPooling option).
+$pooldir = create_pooling_odbcinst();
```
Comment (saurabh500) [inline test/functional/pdo_sqlsrv/pdo_mock_access_token.phpt:39]: Should we be testing without the CPTimeout settings as well?

Comment (saurabh500) [reply test/functional/pdo_sqlsrv/pdo_mock_access_token.phpt:39]: I mean test with default ini, which doesn't have `CPTimeout` ? (ignore if that case is already covered)

**Review by saurabh500 — APPROVED** [review]
Left some comments. Nothing blocking though

File: source/shared/core_conn.cpp (hunk 1 above)
Comment (David-Engel) [reply source/shared/core_conn.cpp:121]: On Windows, if a driver doesn't specify it, the default is 60 seconds. CoPilot picked 120. I didn't argue. On Linux, if a driver doesn't specify CPTimeout, pooling doesn't happen.

File: source/shared/core_sqlsrv.h (hunk 2 above)
Comment (David-Engel) [reply source/shared/core_sqlsrv.h:1061]: Detailed AI response: 

FNV-1a is the right tool here because neither use case needs cryptographic properties:

Token cache lookup — The hash is a fast-rejection filter before `memcmp`. A false positive just means we do one extra comparison. There's no security implication — an attacker can't exploit a hash collision to get a different token's pointer, because the full content comparison is authoritative.

APP pool key — The hash differentiates pool entries in the DM. A collision would mean two different tokens share a pool slot (the original bug). With 64-bit FNV-1a, the birthday-paradox threshold is ~5 billion distinct tokens before a 50% collision probability. A PHP process will never see anywhere near that many.

SHA-256 would add:

A dependency on a crypto library (OpenSSL/BCrypt) or bundling an implementation
~50× slower throughput per byte (SHA-256 ~500 MB/s vs FNV-1a ~25 GB/s on modern CPUs)
A 32-byte output that would need to be truncated or hex-encoded into the connection string anyway
No actual security benefit — the hash isn't protecting against adversarial input. The token content comes from the application's own authentication flow, not from untrusted external sources.
SHA-256 is for when you need collision resistance against an adversary or need a one-way function. Here we just need a fast, well-distributed hash to tell tokens apart. FNV-1a fits that exactly.

File: test/functional/sqlsrv/mock_tds_helper.inc (hunk 4 above)
Comment (David-Engel) [reply test/functional/sqlsrv/mock_tds_helper.inc]: On Windows the standard installer creates python (not python3), while on Linux/macOS python3 is the canonical name and python may point to Python 2 or not exist. But the preference order is just a micro-optimization for skipping one failed exec. It doesn't matter functionally — both candidates are tried regardless.

A single unified array is simpler and works fine. I'll update it.

File: source/shared/core_conn.cpp (hunk 5 above)
Comment (David-Engel) [reply source/shared/core_conn.cpp:1047]: For generic ODBC keywords, the last one wins (spec requirement). For driver-specific keywords, the spec doesn't specify. For APP in MS ODBC SQL, the first APP in the connection string wins (validated). But all entries in the connection string, including duplicates, are considered for the pool key. (We don't block APP.)

File: test/functional/pdo_sqlsrv/pdo_mock_access_token.phpt (hunk 6 above)
Comment (David-Engel) [reply test/functional/pdo_sqlsrv/pdo_mock_access_token.phpt:39]: I considered it. But when pooling is off, as long as we only free the Access Token after disconnect, there's no crash risk and there is no risk of returning the wrong connection from the pool.

**Comment by David-Engel** [comment]
~~Don't merge this, yet. The new test is crashing on macOS (borked). The task to analyze results needs to be updated to detect borked tests.~~

**Review by saurabh500 — APPROVED** [review]
